# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\jagan\plugin\ff\ui_ff.ui'
#
# Created: Fri Jul 12 12:59:28 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ff(object):
    def setupUi(self, ff):
        ff.setObjectName(_fromUtf8("ff"))
        ff.resize(629, 436)
        self.buttonBox = QtGui.QDialogButtonBox(ff)
        self.buttonBox.setGeometry(QtCore.QRect(250, 390, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(ff)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 131, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 26, 81, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 91, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 50, 91, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 80, 101, 17))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 110, 91, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 140, 101, 21))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 220, 101, 17))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 250, 82, 17))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.groupBox_2 = QtGui.QGroupBox(ff)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 60, 141, 301))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 70, 82, 17))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 100, 131, 20))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 130, 82, 17))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 160, 82, 17))
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 190, 82, 17))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 270, 91, 20))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 220, 82, 17))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.toolButton = QtGui.QToolButton(self.groupBox_2)
        self.toolButton.setGeometry(QtCore.QRect(94, 270, 21, 20))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.groupBox_3 = QtGui.QGroupBox(ff)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 60, 121, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.radioButton_17 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_17.setGeometry(QtCore.QRect(10, 80, 101, 17))
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.groupBox_4 = QtGui.QGroupBox(ff)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 190, 121, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_18.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.radioButton_19 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_19.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.radioButton_20 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_20.setGeometry(QtCore.QRect(20, 80, 82, 17))
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(80, 140, 31, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_5 = QtGui.QGroupBox(ff)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 60, 171, 111))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.radioButton_21 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_21.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.radioButton_22 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_22.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton_22.setObjectName(_fromUtf8("radioButton_22"))
        self.radioButton_23 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_23.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.radioButton_23.setObjectName(_fromUtf8("radioButton_23"))
        self.radioButton_24 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_24.setGeometry(QtCore.QRect(90, 20, 82, 17))
        self.radioButton_24.setObjectName(_fromUtf8("radioButton_24"))
        self.radioButton_25 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_25.setGeometry(QtCore.QRect(90, 40, 82, 17))
        self.radioButton_25.setObjectName(_fromUtf8("radioButton_25"))
        self.groupBox_6 = QtGui.QGroupBox(ff)
        self.groupBox_6.setGeometry(QtCore.QRect(440, 190, 161, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 60, 101, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 130, 101, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(40, 40, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_16 = QtGui.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(40, 110, 71, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_4 = QtGui.QLineEdit(ff)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 20, 401, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.toolButton_2 = QtGui.QToolButton(ff)
        self.toolButton_2.setGeometry(QtCore.QRect(450, 20, 151, 21))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))

        self.retranslateUi(ff)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ff.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ff.reject)
        QtCore.QMetaObject.connectSlotsByName(ff)

    def retranslateUi(self, ff):
        ff.setWindowTitle(_translate("ff", "ff", None))
        self.groupBox.setTitle(_translate("ff", "Types of Analysis", None))
        self.label.setText(_translate("ff", "Retrospective", None))
        self.label_2.setText(_translate("ff", "Prospective", None))
        self.radioButton.setText(_translate("ff", "Purely Spatial", None))
        self.radioButton_2.setText(_translate("ff", "Purely Temporal", None))
        self.radioButton_3.setText(_translate("ff", "Space -Time", None))
        self.radioButton_4.setText(_translate("ff", "Spatial Variation", None))
        self.radioButton_5.setText(_translate("ff", "Purily Temporal", None))
        self.radioButton_6.setText(_translate("ff", "Space _Time", None))
        self.label_8.setText(_translate("ff", "in Temporal Trends", None))
        self.groupBox_2.setTitle(_translate("ff", "Probabilty Model", None))
        self.label_3.setText(_translate("ff", "Discrete Scan Statistics", None))
        self.radioButton_7.setText(_translate("ff", "Poisson", None))
        self.radioButton_8.setText(_translate("ff", "Bernoulli", None))
        self.radioButton_9.setText(_translate("ff", "Space-TimePermutation", None))
        self.radioButton_10.setText(_translate("ff", "Multinomial", None))
        self.radioButton_11.setText(_translate("ff", "Ordinal", None))
        self.radioButton_12.setText(_translate("ff", "Exponential", None))
        self.radioButton_14.setText(_translate("ff", "Poisson", None))
        self.radioButton_13.setText(_translate("ff", "Normal", None))
        self.label_5.setText(_translate("ff", "Continuos Scan Statistics", None))
        self.toolButton.setText(_translate("ff", "...", None))
        self.groupBox_3.setTitle(_translate("ff", "Scan for Area With", None))
        self.radioButton_15.setText(_translate("ff", "High Rates", None))
        self.radioButton_16.setText(_translate("ff", "Low Rates", None))
        self.radioButton_17.setText(_translate("ff", "High / Low Rates", None))
        self.groupBox_4.setTitle(_translate("ff", "Time Aggregation", None))
        self.label_4.setText(_translate("ff", "Units", None))
        self.radioButton_18.setText(_translate("ff", "Year", None))
        self.radioButton_19.setText(_translate("ff", "Month", None))
        self.radioButton_20.setText(_translate("ff", "Day", None))
        self.label_6.setText(_translate("ff", "Length", None))
        self.label_7.setText(_translate("ff", "years", None))
        self.groupBox_5.setTitle(_translate("ff", "Time Period", None))
        self.radioButton_21.setText(_translate("ff", "None", None))
        self.radioButton_22.setText(_translate("ff", "Month", None))
        self.radioButton_23.setText(_translate("ff", "Generic", None))
        self.radioButton_24.setText(_translate("ff", "Year", None))
        self.radioButton_25.setText(_translate("ff", "Day", None))
        self.groupBox_6.setTitle(_translate("ff", "Study Period", None))
        self.label_9.setText(_translate("ff", "Start Date", None))
        self.label_10.setText(_translate("ff", "YYYY/MM/DD", None))
        self.label_13.setText(_translate("ff", "End Date", None))
        self.label_16.setText(_translate("ff", "YYYY/MM/DD", None))
        self.toolButton_2.setText(_translate("ff", "browse ...", None))

